### ISSUE TITLE
Humhub 1.16

### ISSUE THREAD

**Issue by mueller-ma** [mriedmann/humhub-docker#356]
Hi, could you update the `latest` tag to 1.16.0?

**Comment by mueller-ma** [comment]
When updating to 1.16, I get the following error:

````
Unknown command: search/rebuild
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "search/rebuild".'

in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php:561

Stack trace:
#0 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#1 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#3 /var/www/localhost/htdocs/protected/yii(31): yii\base\Application->run()
#4 {main}
````

**Comment by kritzi-at** [comment]
the command has changed from `yii search/rebuild` to `yii content-search/rebuild`

**Comment by mueller-ma** [comment]
Thanks for the hint. I created https://github.com/mriedmann/humhub-docker/pull/358.

**Comment by mriedmann** [comment]
Merged and released. It should be fixed.

**Comment by timwsuqld** [comment]
@mriedmann I still have this issue on image a3eb8f463f79 (1.16.1). Is there another tag I should be using to get this fix?

**Comment by mueller-ma** [comment]
I don't have this issue with `ghcr.io/mriedmann/humhub-allinone:1.16.1@sha256:4bb262e82689421a06cfee113a51c91ef4d3885e7dbc90545309ffd0057ac32c`.
But the latest version from a different image has this issue: 
````
$ docker run -it --entrypoint sh mriedmann/humhub:1.16.1
/ # grep search docker-entrypoint.sh
                php yii search/rebuild
````

**Comment by mueller-ma** [comment]
That version doesn't include my commit https://github.com/mriedmann/humhub-docker/commit/87bd1800a70d1bb84c0a8a62540057690396c800:

````
$ docker run -it --entrypoint sh mriedmann/humhub:1.16.1@sha256:0c53cc33b4abf4f6550c2cb1e9aaa321294cbf02bf15af56d2aa70bcfc76345e
/ # grep search docker-entrypoint.sh
                php yii search/rebuild
````

**Comment by timwsuqld** [comment]
`a3eb8f463f79` is the image ID, not the digest.
```
$ docker pull mriedmann/humhub:1.16.1
1.16.1: Pulling from mriedmann/humhub
<snip>
Digest: sha256:0c53cc33b4abf4f6550c2cb1e9aaa321294cbf02bf15af56d2aa70bcfc76345e
Status: Downloaded newer image for mriedmann/humhub:1.16.1
docker.io/mriedmann/humhub:1.16.1
$ docker inspect mriedmann/humhub:1.16.1
[
    {
        "Id": "sha256:a3eb8f463f7939418a56e9cee5803045b2dca815d21a867ec06d7d86eed5447d",
        "RepoTags": [
            "mriedmann/humhub:1.16.1"
        ],
        "RepoDigests": [
            "mriedmann/humhub@sha256:0c53cc33b4abf4f6550c2cb1e9aaa321294cbf02bf15af56d2aa70bcfc76345e"
        ],
<snip>
```

You can see `a3eb8f463f79` in the id, but the digest is `0c53cc33b4abf4f6550c2cb1e9aaa321294cbf02bf15af56d2aa70bcfc76345e`. Annoyingly when you do `docker images` it shows the ID.

@mueller-ma is right though, that base tag doesn't include their fix.

**Comment by zell-mbc** [comment]
I just tried to move up to v1.16 and ran into this issue as well. 
Seeing that the files in this repo have been updated a few times since September and this issue still being closed, am I the only one trying to migrate to v.16?

**Comment by mueller-ma** [comment]
I'm using `ghcr.io/mriedmann/humhub-allinone:1.16.1` which works fine.

**Comment by zell-mbc** [comment]
Thanks for your suggestion @mueller-ma, I ended up mapping the latest docker-entrypoint.sh found here as local file, thus overwriting the docker-entrypoint.sh I get with the image.
So far things seem to be working. Humhub is reporting v.1.16.1 (and complaining about availability of v1.16.2 :-) )

    volumes:
      …
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
  
Still would be good if this could be fixed at some point so I can remove the workaround.

**Comment by zell-mbc** [comment]
The tags are somewhat confusing, there's  humhub:latest which according to the table on the main page is the AllInOne package, but there's also humhub-allinone:version

Anyway, my setup is running and I don't want to be on the very latest release anyway.
